// User Types
const userTypes = {
	FETCH_USERS_REQUESTED: 'FETCH_USERS_REQUESTED',
	FETCH_USERS_SUCCEEDED: 'FETCH_USERS_SUCCEEDED',
	FETCH_USERS_FAILED: 'FETCH_USERS_FAILED',
};

export default userTypes;
